#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_cxx')

def configure(ctx):
    ctx.load('compiler_cxx')

def build(ctx):
    # Copy over everything in our data folder.
    for file in ctx.path.ant_glob('data/**/*'):
        ctx(feature='subst', name='data_' + file.name, rule='cp ${SRC} ${TGT}', source=file, target=file.get_bld())

    ctx.program(source=ctx.path.ant_glob('src/**/*.cpp'),
                target='3drpg_app',
                includes=['include'],
                use=['3drpg'],
                vnum='0.1')
